name: SonarCloud Analysis

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  analysis:
    name: Run analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run SonarCloud analysis
        run: ./gradlew sonar

      - name: SonarCloud Quality Gate check
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}